### PR TITLE
add test meta tags

### PR DESCRIPTION
**Pull request by abriggs-usgs**
Before making a pull request
----------------------------
First . . .
- [x] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Add Meta Data for Social Media Card
-----------
I'm not completely sure this will work. I think we will need to deploy to 'beta' and run it through something like https://socialsharepreview.com/.  Colleen, let me know if I missed anything. I didn't specify the image size since the image was formatted for social media already.

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by abriggs-usgs** [comment]
Let's give it a try.

**Comment by jread-usgs** [comment]
quick q - this is a pretty big file for a thumbnail. Is is load/paint-blocking?

**Comment by abriggs-usgs** [comment]
That is a good question. I ran it locally and it didn't seem affect the build time or the loading speed. The files for the images are stored in the 'public' directory and that is not processed by Webpack. So while they will sit on the server, I don't think they are loaded on page load. But I need to confirm this.

**Comment by jread-usgs** [comment]
Cool - we've often been interested in trying a gif as a thumbnail because it might be more eye-catching, but never got far enough along to understand the tradeoffs between that and a smaller static file. Would be good to know.

**Comment by abriggs-usgs** [comment]
As a followup, for reasons I don't understand,  I was unable to get the files stored in the 'public' folder of the application to load correctly. The 'public' is where the USGS logo for the favicon is stored and that works in combination with an environment variable called BASE_URL  which is what tells Vue what directory the application is located in when/if it not deployed at the root of the URL (as it is not for labs.waterdata.usgs.gov/visualizations). So as a simple work around, I used our assets server (the one we use for hill shade) to serve the files. While this adds a level of complexity due to having the images outside of the application, it does guarantee that the files don't interfere with the build process. I did check the network use when the visualization is loaded and it appears that the files are only used when the meta data is used in social media.

**Comment by collnell** [comment]
Hmm interesting. Is that reflected in the `<meta>` tags here? Are you still able to direct  to them with `<%= BASE_URL %>` when they are sourced from the server?

**Comment by abriggs-usgs** [comment]
The changes to use the server are in this pull request, https://github.com/usgs-makerspace/gages-through-the-ages/pull/202 . It is the same server that was mentioned in our tutorial on AWS deployment.

**Pull request merged**
