### PR TITLE
inserted infographic as svg, made it a component

### PR DESCRIPTION
**Pull request by ellenbechtel**
Before making a pull request
----------------------------
First . . .
- [x] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Inserted SVG of infographic
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Saved infographic.svg in assets folder
Made Vue see infographic.svg as an individual component
Did NOT know why Vue is incorrectly reading the CSS styling of each path, and is instead defaulting them as black fill

-----------
If no ticket is referenced, describe the changes made. Note anything that you want the reviewers to know while
reviewing your pull request

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Related: @ellenbechtel mentioned that the CSS classes are not being used by Vue so I have been investigating. I think there are two strategies: 

1. Get Vue to recognize these CSS classes (there are like 95...) that come with this particular SVG by doing something fancy with https://github.com/svg/svgo#what-it-can-do. I fiddled with `addClassesToSVGElement` but didn't get very far.
2. Re-export the SVG so that the information from the classes are stored in `style = ` for each SVG element, see [this Stackoverflow comment](https://stackoverflow.com/a/57734881)
3. Lastly, we can just cut and paste all of the CSS classes from the SVG into the `<style>` section for the Vue component (I have tested this and it works).

What do people think is the best solution?

**Comment by ellenbechtel** [comment]
@lindsayplatt I can definitely re-export the svg!  Here it is, if you want to save it in the assets folder and just try it out. 

[infographic-inline.zip](https://github.com/usgs-makerspace/gages-through-the-ages/files/5057538/infographic-inline.zip)
(I saved it as a .zip because apparently github doesn't support linking .svg???)

Worst case, Option 3 sounds like it would work, even though it's the brute-force method.  I feel pretty confident knowing which pieces are which though, so if you don't want to spend time on it, that's something I could probably do pretty quickly today.

**Comment by lindsayplatt** [comment]
@ellenbechtel I did the option 3, brute force method yesterday (see #160) and it seems to mostly work - just the text is funky. You can look at it on test now. I will try using the inline version locally and see if that is an improvement!

**Comment by ellenbechtel** [comment]
Fab.  Let me know if you still have lingering issues, especially with the font connection and just need a second pair of eyes this afternoon.

**Comment by lindsayplatt** [comment]
So the inline version doesn't carry the font styling that I would expect either. Here it is running locally:

image

I think @collnell is going to spearhead this part ... I know very little about CSS.

**Comment by collnell** [comment]
Totally happy to take a crack at the svg here. I think some things are a product of Illustrator export that I have experienced myself before. For a lot of the text, different classes were added to consecutive letters in a word in some places and the classes are adding letter spacing changes. I think most of that just needs to be stripped from it

**Pull request merged**
