### PR TITLE
attempt to add social images from server

### PR DESCRIPTION
**Pull request by abriggs-usgs**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Attempt to Add Social Media Images from Server
-----------
The attempt add the social media images failed when using the BASE_URL variable. I am not sure why this is as it works correctly when loading favicon from the public directory.

However, when I tested this with https://metatags.io/ it returned a 404 for the images. All of the rest of the social media meta tags worked as expected. The only difference between how the favicon (which works) is set up and the social media images (which don't work) is that the social media images are in a content rather tag rather than an href. I do not see why this would affect the function of the BASE_URL variable, however it clearly does as the href returns the desired base of labs-beta.waterdata.usgs.gov while the content tag returns the base URL of https://metatags.io/ . As an alternative, I added the social media images to our static assets server, and will see if the images will work when served from that location.

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by abriggs-usgs** [comment]
I'll merge this, since it mainly experimental.

**Comment by abriggs-usgs** [comment]
Success! 
image

**Comment by collnell** [comment]
Do you know if the card would work if we wanted to direct it to a image file that is within the app elsewhere, like in the assets, by using the absolute path?

**Comment by abriggs-usgs** [comment]
I'm thinking it would work if we put the file in either the 'public' or 'static' folder as both are not processed by Webpack, but I don't think the BASE_URL variable will work (unless we can spot some error in the syntax). We would need (I think) to hard code in the full URL in the same manner as I did with the files stored on the assets server, so in effect there wouldn't be much difference and storing the files on the assets server allows us to swap them in and out without having to rebuild 'beta' which is actually a bit advantage for troubleshooting.

**Comment by abriggs-usgs** [comment]
Oh, thinking about ☝, if you think that changing the file size or whatever will help, you can send the changes to me and I can swap the new files with those on the assets server (since you don't have AWS access) and we can test the effects immediately.

**Pull request merged**
