### PR TITLE
Minor infographic text change

### PR DESCRIPTION
**Pull request by jread-usgs**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate
Minor infographic text change.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Hmm so this conflicts a bit with the edit that Chad had us make to the flood forecasting one. It now says "Will the road flood?" ...

**Comment by lindsayplatt** [comment]
He had us change from a coastal emphasis because we don't have many coastal gages. Maybe we can pick a different forecasting question ... like "Where will there be flooding?" or something

**Comment by jread-usgs** [comment]
well shoot. I didn't see that. I thought our original one for floods was "how high will the water get?"

**Comment by lindsayplatt** [comment]
I like that edited flood message

**Pull request merged**
